Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

Load Dataset

In [2]:
df = pd.read_csv("E-Commerce-Customer.csv")

Inspect Structure

In [3]:
print ("Shape:", df.shape)
print("\nColumns:")
print(df.columns)
print("\nFirst 5 rows:") 
display(df.head())
print("\nDataset Information:")
df.info()

Shape: (3599, 10)

Columns:
Index(['CustomerID', 'Gender', 'InvoiceDate', 'InvoiceNumber', 'ProductID',
       'Quantity', 'Price', 'Total', 'Country', 'DeviceCategory'],
      dtype='str')

First 5 rows:

,CustomerID,Gender,InvoiceDate,InvoiceNumber,ProductID,Quantity,Price,Total,Country,DeviceCategory
0,9691,Female,01-01-2019,26088332,32,3,91.37,274.11,India,Computer
1,8327,Female,01-01-2019,95183269,34,1,48.24,48.24,India,Computer
2,6801,Male,01-01-2019,44769684,64,2,35.23,70.46,United States,Computer
3,4406,Male,01-02-2019,12422351,41,2,32.33,64.66,Philippines,Mobile
4,1966,Male,01-03-2019,84352310,20,1,81.89,81.89,Brazil,Computer

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 3599 entries, 0 to 3598
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerID      3599 non-null   int64
 1   Gender          3599 non-null   str
 2   InvoiceDate     3599 non-null   str
 3   InvoiceNumber   3599 non-null   int64
 4   ProductID       3599 non-null   int64
 5   Quantity        3599 non-null   int64
 6   Price           3599 non-null   float64
 7   Total           3599 non-null   float64
 8   Country         3599 non-null   str
 9   DeviceCategory  3599 non-null   str
dtypes: float64(2), int64(4), str(4)
memory usage: 281.3 KB

Missing Values

In [4]:
print("Missing values:")
print(df.isnull().sum())
print("\nDuplicate rows:",df.duplicated().sum())

Missing values:
CustomerID        0
Gender            0
InvoiceDate       0
InvoiceNumber     0
ProductID         0
Quantity          0
Price             0
Total             0
Country           0
DeviceCategory    0
dtype: int64

Duplicate rows: 0

Handle Missing/Inconsistent Data

In [5]:
df = df.drop_duplicates()
numeric_cols = df.select_dtypes(include=np.number).columns
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].median())
print("Missing values after cleaning:")
print(df.isnull().sum())

Missing values after cleaning:
CustomerID        0
Gender            0
InvoiceDate       0
InvoiceNumber     0
ProductID         0
Quantity          0
Price             0
Total             0
Country           0
DeviceCategory    0
dtype: int64

Descriptive Statistics

In [6]:
df.describe()

,CustomerID,InvoiceNumber,ProductID,Quantity,Price,Total
count,3599.000000,3.599000e+03,3599.000000,3599.000000,3599.000000,3599.000000
mean,5526.962767,5.582117e+07,50.864962,2.000556,48.714571,97.394143
std,2586.425565,2.568169e+07,29.035862,0.813313,29.499165,74.421471
min,1111.000000,1.114055e+07,1.000000,1.000000,1.220000,1.220000
25%,3288.000000,3.355699e+07,26.000000,1.000000,26.030000,37.610000
50%,5546.000000,5.614293e+07,52.000000,2.000000,43.500000,81.460000
75%,7777.000000,7.810160e+07,76.000000,3.000000,74.550000,147.060000
max,9998.000000,9.996354e+07,100.000000,3.000000,99.720000,299.160000

Average Purchase Value

In [7]:
print("Average Purchase Value:",df["Total"].mean())

Average Purchase Value: 97.39414281744929

Customer Lifetime

In [8]:
customer_lifetime = df.groupby("CustomerID")["Total"].sum()
print("Average Customer Lifetime Value:",customer_lifetime.mean())

Average Customer Lifetime Value: 118.37943937858832

Purchase Frequency

In [9]:
purchase_frequency = df.groupby("CustomerID")["InvoiceNumber"].nunique()
print("Average Purchase Frequency:",purchase_frequency.mean())

Average Purchase Frequency: 1.215467747382641

Behavioural Features